services:
  postgres:
    image: postgres:15.1
    restart: unless-stopped
    env_file:
      - .env.template
    ports:
      - 5432:5432
  api:
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env.template
    ports:
      - 8000:8000
