services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  api:
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
